//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeskHealthApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeskHealthApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StreImgEXP1 {
            get {
                object obj = ResourceManager.GetObject("StreImgEXP1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StreImgExp2 {
            get {
                object obj = ResourceManager.GetObject("StreImgExp2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  1.   Remaining seated, extend one leg outward.
        /// 2.   Reach toward your toes.
        /// 3.   Hold for 10 to 30 seconds.
        /// 4.   Repeat on the other side.
        ///
        ///Be sure to do this one leg at a time, as doing this exercise with both legs out can cause back issues..
        /// </summary>
        internal static string StretchHamstring {
            get {
                return ResourceManager.GetString("StretchHamstring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shoulder, or pectoralis stretch
        ///    Clasp hands behind your back.
        ///    Push the chest outward, and raise the chin.
        ///    Hold the pose for 10 to 30 seconds..
        /// </summary>
        internal static string StretchTxt1 {
            get {
                return ResourceManager.GetString("StretchTxt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tricep
        ///    Raise your arm and bend it so that your hand reaches toward the opposite side.
        ///    Use your other hand and pull the elbow toward your head.
        ///    Hold for 10 to 30 seconds.
        ///    Repeat on the other side..
        /// </summary>
        internal static string StreTxt2 {
            get {
                return ResourceManager.GetString("StreTxt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trunk Rotation
        ///    Keep your feet firmly on the ground, facing forward.
        ///    Twist your upper body in the direction of the arm that’s resting on the back of your chair.
        ///    Hold pose for 10 to 30 seconds.
        ///    Repeat on other side.
        ///
        ///Tip: Exhale as you lean into the stretch for a greater range of motion..
        /// </summary>
        internal static string StreTxt3 {
            get {
                return ResourceManager.GetString("StreTxt3", resourceCulture);
            }
        }
    }
}
